image: fedora:latest

before_script: 
  # Update packages
  - dnf -y update

analysisAndTest:
  stage: build
  script:
    # Install compiler and analysis tools
    - dnf install -y cmake clang clang-analyzer clazy cppcheck gcc-c++ git make
    # Install project dependencies
    - dnf install -y qt5-qtbase-devel qt5-qtsvg-devel qt5-linguist qt5-qtquickcontrols2-devel
    # Go …
    - ./analyze-and-test.sh
  artifacts:
    paths:
      - testResults

analysisAndTest:evaluate:
  dependencies:
    - analysisAndTest
  script:
    # Fail if the directory "testResults" contains anything
    - if [ -d testResults ] ; then exit -1; fi
