# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools


default_platform(:android)

platform :android do
  desc "Build Android Binary"
  lane :build do
    Dir.chdir("..") do
      sh "./buildscript-android-release.sh"
    end
  end

  desc "Updata Meta Data for Google Play"
  lane :metadata do
    # Update Changelog files
    matches = File.read("../CHANGELOG.md").scan(/^## \s*\[?(.*?)\]?\s*-\s*.*?\n(.*?)(?=^## |\z)/m)
    latest_version, changelog_text = matches.last
    major, minor, patch = latest_version.split('.').map(&:to_i)
    version_code = 100000 * major + 1000 * minor + patch
    File.write("metadata/android/en-US/#{version_code}.txt", changelog_text.strip)      
  end

  desc "Deploy a new version to Google Play - Beta"
  lane :deployBeta do
    build
    metadata
    #upload_to_play_store
  end
end
