name: add-hours-and-minutes # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
adopt-info: addhoursandminutes
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0

apps:
  addhoursandminutes:
    command: usr/bin/addhoursandminutes
    common-id: de.akaflieg_freiburg.cavok.add_hours_and_minutes
    desktop: usr/share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop
    extensions:
      - kde-neon    
    plugs:
      - opengl
      - kde-frameworks-5-plug
      
parts:
  addhoursandminutes:
    parse-info:
      - usr/share/appdata/de.akaflieg_freiburg.cavok.add_hours_and_minutes.appdata.xml
    plugin: cmake
    source: https://github.com/Akaflieg-Freiburg/addhoursandminutes.git
    source-type: git
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    build-packages:
      - libmpfr-dev
      - libgmp-dev
      - kdoctools-dev
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
