name: add-hours-and-minutes # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
adopt-info: addhoursandminutes
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0

apps:
  addhoursandminutes:
    command: bin/desktop-launch addhoursandminutes
    common-id: de.akaflieg_freiburg.cavok.add_hours_and_minutes
    desktop: share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop
    plugs:
      - opengl
      - network
      - network-bind
      
parts:
  addhoursandminutes:
    parse-info:
      - $SNAPCRAFT_PART_INSTALL/share/metainfo/de.akaflieg_freiburg.cavok.add_hours_and_minutes.appdata.xml
    plugin: cmake
    source: https://github.com/Akaflieg-Freiburg/addhoursandminutes.git
    source-type: git
    build-packages:
      - libqt5svg5-dev
      - pkg-config
      - qtbase5-dev
      - qtdeclarative5-dev
      - qttools5-dev
      - qttools5-dev-tools
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL
      - -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake
    stage-packages:
      - qt5-default

