name: add-hours-and-minutes
base: core22
adopt-info: addhoursandminutes
grade: stable
confinement: strict
license: GPL-3.0
architectures: [amd64]

apps:
  add-hours-and-minutes:
    command: bin/addhoursandminutes
    common-id: de.akaflieg_freiburg.cavok.add_hours_and_minutes
    desktop: share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop
    plugs:
      - opengl

parts:
  qtbase:
    source: https://github.com/qt/qtbase.git
    source-type: git
    source-tag: v6.4.2
    build-snaps:
      - cmake
    build-packages:
      - libfontconfig1-dev
      - libfreetype6-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxrender-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-keysyms1-dev
      - libxcb-image0-dev
      - libxcb-shm0-dev
      - libxcb-icccm4-dev
      - libxcb-sync-dev
      - libxcb-xfixes0-dev
      - libxcb-shape0-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-util-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libgl1-mesa-dev
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libx11
      - libx11-xcb
      - libxext
      - libxfixes
      - libxi
      - libxrender
      - libxcb1
      - libxcb-glx0
      - libxcb-keysyms1
      - libxcb-image0
      - libxcb-shm0
      - libxcb-icccm4
      - libxcb-sync
      - libxcb-xfixes0
      - libxcb-shape0
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-util
      - libxcb-xinerama0
      - libxcb-xkb
      - libxkbcommon
      - libxkbcommon-x11
      - libgl1-mesa
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
  qtsvg:
    source: https://github.com/qt/qtsvg.git
    source-type: git
    source-tag: v6.4.2
    after:
      - qtbase
    build-snaps:
      - cmake
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
  qttools:
    source: https://github.com/qt/qttools.git
    source-type: git
    source-tag: v6.4.2
    after:
      - qtbase
    build-snaps:
      - cmake
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF
      - -DQT_BUILD_TESTS_BY_DEFAULT=OFF
      - -DFEATURE_assistant=ON
      - -DFEATURE_clang=OFF
      - -DFEATURE_clangcpp=OFF
      - -DFEATURE_designer=ON
      - -DFEATURE_distancefieldgenerator=OFF
      - -DFEATURE_kmap2qmap=OFF
      - -DFEATURE_macdeployqt=OFF
      - -DFEATURE_pixeltool=OFF
      - -DFEATURE_pkg_config=OFF
      - -DFEATURE_qdbus=OFF
      - -DFEATURE_qev=OFF
      - -DFEATURE_qtattributionsscanner=OFF
      - -DFEATURE_qtdiag=OFF
      - -DFEATURE_qtplugininfo=OFF
      - -DFEATURE_windeployqt=OFF
  qtshadertools:
    source: https://github.com/qt/qtshadertools.git
    source-type: git
    source-tag: v6.4.2
    after:
      - qtbase
    build-snaps:
      - cmake
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
  qtdeclarative:
    source: https://github.com/qt/qtdeclarative.git
    source-type: git
    source-tag: v6.4.2
    after:
      - qtbase
      - qtshadertools
    build-environment: &buildenv
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET:/usr/lib/$CRAFT_ARCH_TRIPLET${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    build-snaps:
      - cmake
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
  addhoursandminutes:
    after:
      - qtbase
      - qtdeclarative
      - qtsvg
      - qttools
    parse-info:
      - share/appdata/de.akaflieg_freiburg.cavok.add_hours_and_minutes.appdata.xml
    plugin: cmake
    source: .
    build-packages:
      - libglvnd-dev
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
    override-build: |
      snapcraftctl build
      sed -i.bak -e 's|Icon=de.akaflieg_freiburg.cavok.add_hours_and_minutes|Icon=share/icons/hicolor/scalable/apps/de.akaflieg_freiburg.cavok.add_hours_and_minutes.svg|g' $SNAPCRAFT_PART_INSTALL/share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop
