name: add-hours-and-minutes # you probably want to 'snapcraft register <name>'
base: core20
adopt-info: addhoursandminutes
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0

apps:
  addhoursandminutes:
    command: usr/bin/addhoursandminutes
    common-id: de.akaflieg_freiburg.cavok.add_hours_and_minutes
    desktop: usr/share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop
    plugs:
      - opengl
      
parts:
  addhoursandminutes:
    parse-info:
      - usr/share/appdata/de.akaflieg_freiburg.cavok.add_hours_and_minutes.appdata.xml
    plugin: cmake
    source: https://github.com/Akaflieg-Freiburg/addhoursandminutes.git
    source-type: git
    build-packages:
      - libqt5svg5-dev
      - pkg-config
      - qtbase5-dev
      - qtdeclarative5-dev
      - qttools5-dev
      - qttools5-dev-tools
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
    stage-packages:
      - qt5-default
      - libqt5qml5
