name: add-hours-and-minutes
base: core18
adopt-info: addhoursandminutes
grade: stable
confinement: strict
license: GPL-3.0

apps:
  add-hours-and-minutes:
    command: bin/addhoursandminutes
    common-id: de.akaflieg_freiburg.cavok.add_hours_and_minutes
    desktop: share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop
    plugs:
      - opengl
    extensions:
      - kde-neon
      
parts:
  addhoursandminutes:
    parse-info:
      - share/appdata/de.akaflieg_freiburg.cavok.add_hours_and_minutes.appdata.xml
    plugin: cmake
    source: .
    build-snaps:
      - kde-frameworks-5-core18-sdk
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
    override-build: |
      snapcraftctl build
      sed -i.bak -e 's|Icon=de.akaflieg_freiburg.cavok.add_hours_and_minutes|Icon=share/icons/hicolor/scalable/apps/de.akaflieg_freiburg.cavok.add_hours_and_minutes.svg|g' $SNAPCRAFT_PART_INSTALL/share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop
