name: add-hours-and-minutes
base: core20
adopt-info: addhoursandminutes
grade: stable
confinement: strict
license: GPL-3.0

apps:
  addhoursandminutes:
    command: bin/desktop-launch addhoursandminutes
    common-id: de.akaflieg_freiburg.cavok.add_hours_and_minutes
    desktop: share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop
    plugs:
      - opengl
      
parts:
  addhoursandminutes:
    after:
      - desktop-qt5
    parse-info:
      - share/appdata/de.akaflieg_freiburg.cavok.add_hours_and_minutes.appdata.xml
    plugin: cmake
    source: https://github.com/Akaflieg-Freiburg/addhoursandminutes.git
    source-type: git
    build-packages:
      - libqt5svg5-dev
      - pkg-config
      - qtbase5-dev
      - qtdeclarative5-dev
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - libqt5qml5
      - libqt5quickcontrols2-5
      - libqt5svg5
      - qml-module-qtquick2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-extras
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick-controls2
      - qt5-default
    override-build: |
      cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL \
        -DCMAKE_PREFIX_PATH=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install
      sed -i.bak -e 's|Icon=de.akaflieg_freiburg.cavok.add_hours_and_minutes|Icon=share/icons/hicolor/scalable/apps/de.akaflieg_freiburg.cavok.add_hours_and_minutes.svg|g' $SNAPCRAFT_PART_INSTALL/share/applications/de.akaflieg_freiburg.cavok.add_hours_and_minutes.desktop

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
