name: Compile on Android

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "CHANGELOG.md"
      # ignore CI for other platforms
      - ".github/workflows/ios.yml"
      - ".github/workflows/linux.yml"
      - ".github/workflows/macos.yml"
      - ".github/workflows/windows.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Qt for Android arm64
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.2.*'
        cache: 'true'
        cache-key-prefix: 'install-qt-action-android'
        target: 'android'
        version: '6.9.3'
        arch: 'android_arm64_v8a'
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@v5
    - name: Remove Unwanted Software
      run: |
        echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall "platforms;android-33-ext4" "platforms;android-33-ext5" "platforms;android-34-ext8"
    - name: Configure
      run: |
        export QT_HOST_PATH="$(readlink -f "$QT_ROOT_DIR/../gcc_64")"
        cmake -E make_directory build
        $QT_ROOT_DIR/bin/qt-cmake -DCMAKE_BUILD_TYPE:STRING=Debug -S . -B build
    - name: Compile
      run: |
        cmake --build build
        cmake --build build --target apk
        cp build/src/android-build/build/outputs/apk/debug/android-build-debug.apk addTimes-android-arm64v8a.apk
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds addTimes-android-arm64v8a.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
