name: Compile on Android

on:
  create:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Qt for Desktop
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.4.1'
    - name: Set QT_HOST_PATH
      run: |
        echo QT_HOST_PATH=$Qt6_DIR >> $GITHUB_ENV
    - name: Install Qt for Android
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        version: '6.4.1'
        arch: 'android_arm64_v8a'
    - name: Install Additional Software
      run: |
        sudo apt install doxygen graphviz librsvg2-bin
        echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;22.1.7171670"
        echo ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/22.1.7171670 >> $GITHUB_ENV
    - name: Configure
      run: |
        mkdir -p build
        cd build
        $Qt6_DIR/bin/qt-cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug
    - name: Compile
      run: |
        cd build
        make
        make apk
    - uses: actions/upload-artifact@v1
      if: github.event_name == 'push'
      with:
        name: Debug-APK
        path: build/src/android-build//build/outputs/apk/debug/android-build-debug.apk
