name: Compile on Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        version: '6.3.1'
        arch: 'android_armv7'
        cached: 'false'
    - name: Install Additional Software
      run: |
        sudo apt install doxygen graphviz librsvg2-bin
    - name: Configure
      run: |
        mkdir -p build
        cd build
        ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/22.1.7171670
        $Qt6_DIR/bin/qt-cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug
    - name: Compile
      run: |
        cd build
        make
        make apk
    - uses: actions/upload-artifact@v1
      if: github.event_name == 'push'
      with:
        name: Debug-APK
        path: build/android-build/build/outputs/apk/debug/android-build-debug.apk
