name: Compile on Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        version: '6.2'
        arch: 'android_armv7'
    - name: Install Additional Software
      run: |
        sudo apt install doxygen graphviz librsvg2-bin
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DANDROID_ABI:STRING=armeabi-v7a \
          -DANDROID_BUILD_ABI_arm64-v8a:BOOL=OFF \
          -DANDROID_BUILD_ABI_armeabi-v7a:BOOL=ON \
          -DANDROID_BUILD_ABI_x86:BOOL=OFF \
          -DANDROID_BUILD_ABI_x86_64:BOOL=OFF \
          -DANDROID_NATIVE_API_LEVEL:STRING=23 \
          -DANDROID_NDK:PATH=$ANDROID_SDK_ROOT/ndk/23.2.8568313 \
          -DANDROID_SDK:PATH=$ANDROID_SDK_ROOT \
          -DANDROID_STL:STRING=c++_shared \
          -DCMAKE_BUILD_TYPE:STRING=Debug \
          -DCMAKE_CXX_COMPILER:STRING=$ANDROID_SDK_ROOT/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ \
          -DCMAKE_C_COMPILER:STRING=$ANDROID_SDK_ROOT/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
          -DCMAKE_FIND_ROOT_PATH:STRING=$Qt6_DIR \
          -DCMAKE_PREFIX_PATH:STRING=$Qt6_DIR \
          -DCMAKE_TOOLCHAIN_FILE:PATH=$ANDROID_SDK_ROOT/ndk/23.2.8568313/build/cmake/android.toolchain.cmake \
          -DQT_QMAKE_EXECUTABLE:STRING=$Qt6_DIR/bin/qmake
        cmake ..
    - name: Compile
      run: |
        cd build
        make
        make apk
    - uses: actions/upload-artifact@v1
      if: github.event_name == 'push'
      with:
        name: Debug-APK
        path: build/android-build/build/outputs/apk/debug/android-build-debug.apk
