name: Compile on iOS

on:
  create:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  APPLICATION: "addhoursandminutes"

jobs:
  build:

    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true 
    - name: Install Qt for Desktop
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.3.1'
    - name: Set QT_HOST_PATH
      run: |
        echo QT_HOST_PATH=$Qt6_DIR >> $GITHUB_ENV
    - name: Install Qt for iOS
      uses: jurplel/install-qt-action@v2
      with:
        target: 'ios'
        version: '6.3.1'
    - name: Setup env
      run: |
        export PATH=$Qt6_DIR/bin:$PATH
        ln -s /Users/runner/work/${{env.APPLICATION}}/Qt/6.3.1/macos /Users/runner/work/${{env.APPLICATION}}/Qt/6.3.1/clang_64
        qmake --version
    - name: Configure
      run: |
        cmake -E make_directory build
        cd build
        $Qt6_DIR/bin/qt-cmake .. -DCMAKE_BUILD_TYPE=Debug
    - name: Compile
      run: |
        cd build
        cmake --build .
