name: Compile on iOS-Simulator

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "CHANGELOG.md"
      # ignore CI for other platforms
      - ".github/workflows/android.yml"
      - ".github/workflows/linux.yml"
      - ".github/workflows/macos.yml"
      - ".github/workflows/windows.yml"

env:
  APPLICATION: "addhoursandminutes"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Qt for Desktop
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-macOS-host'
        version: '6.9.3'
    - name: Set QT_HOST_PATH
      run: |
        echo QT_HOST_PATH=$QT_ROOT_DIR >> $GITHUB_ENV
    - name: Install Qt for iOS
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-ios'
        target: 'ios'
        version: '6.9.3'
    - name: Configure
      run: |
        cmake -E make_directory build
        $Qt6_DIR/bin/qt-cmake -S . -B build
    - name: Compile
      run: |
        cd build
        cmake --build . -- -sdk iphonesimulator
    - name: Package
      run: |
        brew install create-dmg
        create-dmg addTimes-iphonesimulator.dmg build/src/Debug-iphonesimulator
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds addTimes-iphonesimulator.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
