name: Compile on iOS

on:
  push:
    branches: [ feature/actions ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Qt for iOS
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        target: 'ios'
        version: '6.*.*'
    - name: Configure
      run: |
        cmake -E make_directory build
        $Qt6_DIR/bin/qt-cmake -S . -B build
    - name: Compile
      run: |
        cd build
        cmake --build . -- -sdk iphonesimulator
    - name: Package
      run: |
        brew install create-dmg
        create-dmg addTimes-iphonesimulator.dmg build/src/Debug-iphonesimulator
   - name: Upload to developerBuilds
        run: |
            gh release upload --clobber developerBuilds addTimes-iphonesimulator.dmg‚
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
