name: Compile on Linux

on:
  create:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.*'
    - name: Install Additional Software
      run: |
        sudo apt update
        sudo apt install doxygen graphviz
    - name: Configure and Compile
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        cmake -E make_directory build
        cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
        cmake --build build
