name: Compile on Linux

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "CHANGELOG.md"
      # ignore CI for other platforms
      - ".github/workflows/android.yml"
      - ".github/workflows/ios.yml"
      - ".github/workflows/macos.yml"
      - ".github/workflows/windows.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Enroute
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: ==3.1.*
        cache: 'true'
        version: '6.9.3'
    - name: Install LinuxDeploy
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: appimage
    - name: Install Additional Software
      run: |
        sudo apt install appstream fuse libxcb-cursor0
    - name: Configure
      run: |
        cmake -E make_directory build
        $QT_ROOT_DIR/bin/qt-cmake \
          -DQTDEPLOY=ON \
          -DCMAKE_INSTALL_PREFIX:STRING=$PWD/app/usr \
          -DCMAKE_BUILD_TYPE:STRING=Release \
          -S . \
          -B build
    - name: Compile and Install
      run: |
        cmake --build build
        cmake --build build --target install
    - name: Package
      run: |
        linuxdeploy-x86_64.AppImage --appdir app --output appimage
        mv Add_Times-x86_64.AppImage addTimes-Linux.AppImage
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds addTimes-Linux.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
