name: Compile on Linux

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true 
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        version: '6.7.1'
    - name: Install LinuxDeploy
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: appimage
    - name: Install Additional Software
      run: |
        sudo apt install appstream fuse libxcb-cursor0
    - name: Configure
      run: |
        cmake -E make_directory build
        $QT_ROOT_DIR/bin/qt-cmake -DCMAKE_INSTALL_PREFIX:STRING=$PWD/app/usr -DCMAKE_BUILD_TYPE:STRING=Debug -S . -B build
    - name: Compile and Install
      run: |
        cmake --build build
        cmake --build build --target install
    - name: Package
      run: |
        linuxdeploy-x86_64.AppImage --appdir app --output appimage
        mv Add_Times-x86_64.AppImage addTimes-Linux.AppImage
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds addTimes-Linux.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
