name: Compile on Linux

on:
  create:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.4.1'
    - name: Install Additional Software
      run: |
        sudo apt update
        sudo apt install doxygen graphviz
    - name: Configure
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        cmake -E make_directory build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-Werror -Wall -Wextra'
    - name: Test-compile on standard Linux
      run: |
        cd build
        make VERBOSE=1
