name: Compile on MacOS

on:
  create:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.3.1'
    - name: Configure
      run: |
        cmake -E make_directory build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
    - name: Compile
      run: |
        cd build
        make VERBOSE=1
