name: Compile on MacOS

on:
  push:
    branches: [ main, feature/actions ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.*.*'
    - name: Configure
      run: |
        cmake -E make_directory build
        $Qt6_DIR/bin/qt-cmake -DCMAKE_BUILD_TYPE:STRING=Debug -S . -B build
    - name: Compile
      run: |
        cmake --build build
