name: Compile on Windows

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true 
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        version: '6.7.*'
    - name: Configure
      run: |
        cmake -E make_directory build
        qt-cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_INSTALL_PREFIX:STRING=${{ github.workspace }}\addTimes -S . -B build
    - name: Compile
      run: |
        cmake --build build
    - name: Install
      run: |
        cmake --build build --target install
    - name: Package
      run: |
        powershell Compress-Archive addTimes addTimes-windows64.zip
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds addTimes-windows64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
